### ISSUE TITLE
Can multiple indices display one set of results?

### ISSUE THREAD

**Issue by MaartenAnckaert** [algolia/react-instantsearch#643] opened 2017-11-23 16:31 UTC
I want to perform a search on multiple indices and display the results in an unrelated manner. When I try it like I did below. I only get results from 'person_manualUpload'. 

```jsx
<InstantSearch appId="" apiKey="" indexName="Person_manualUpload">
  <Index indexName="Movie_manualUpload" />
  <Index indexName="Serie_manualUpload" />
  <View style={styles.textInputContainer}>
    <View style={styles.searchImageContainer}>
      <Image style={styles.searchImage} source={iconSearch} />
    </View>
    <SearchBox />
  </View>
  <Results />
</InstantSearch>
```

However when I try it like this, I can search the multiple indices, but the results are displayed seperate of one an other:

```jsx
<InstantSearch appId="" apiKey="" indexName="Person_manualUpload">
  <View style={styles.textInputContainer}>
    <View style={styles.searchImageContainer}>
      <Image style={styles.searchImage} source={iconSearch} />
    </View>
    <SearchBox />
  </View>
  <Results />
  <Index indexName="Movie_manualUpload">
    <Results />
    <Index indexName="Serie_manualUpload">
      <Results />
    </Index>
  </Index>
</InstantSearch>
```

Some help would be greatly appreciated :) .

**Comment by samouss** [comment] 2017-11-23 17:08
Hi @MaartenAnckaert,

I'm not sure to understand correctly your needs, the results is always separate from the others. You can't display results from one index mixed with another one. There is no way to properly sort which one is the more relevant.

On the first snippet it's the intended behaviour. The `<Results />` component is scoped under `<InstantSearch />` so the results will come from this index. If you want to display results related to an other index you need to nest the `<Results />` component under `<Index />`like that: 

```jsx
<InstantSearch indexName="Person_manualUpload">
  <SearchBox />

  <Results />

  <Index indexName="Movie_manualUpload">
    <Results />
  </Index>

  <Index indexName="Serie_manualUpload">
    <Results />
  </Index>
</InstantSearch>
```

It will render one `<SearchBox />` shared across the three indices, and it will render three list of hits one for each index.

**Comment by MaartenAnckaert** [comment] 2017-11-23 19:00
Hey @samouss , thanks for your prompt reply!! This is what I noticed aswel and I was wondering if it was at all possible to mix results. Maybe I'll just need to normalise some data and push it all to one index if I want them all to be mixed then . :)

**Comment by samouss** [comment] 2017-11-23 20:05
That’s definitely an option. I will close this issue, feel free to re-open if needed 😉

**Closed by samouss** 2017-11-23 20:05 UTC

**Comment by Haroenv** [comment] 2017-11-24 06:45
Exactly, having them sorted across indices or mixed can only make sense if they’re all sorted in the same way. For that to be possible there should be a single index only. Multiple indices is to create an experience with separate results for separate data, like songs and artists
