### ISSUE TITLE
useRange not returning any values.

### ISSUE THREAD

**Issue by The-Code-Monkey** [algolia/react-instantsearch#3571] opened 2022-07-19 15:58 UTC
## 🐛 Bug description

I'm trying to convert from the old HOC version and convert to hooks, the HOC version worked but the hook version gives the response from below.

What happens is we have some values that are range values and this doesn't work.

This is the console log that i've done.
```
const {
    range: { min, max },
    start: [minValue, maxValue],
    canRefine,
    refine,
} = useRange({ attribute: category });

console.log('HERE', category, min, max, minValue, maxValue, canRefine);

'HERE' milge 0 0 -Infinity Infinity false
```

## 🔍 Bug reproduction

Nothing public that can be worked on. Unfortunately.

## 💭 Expected behavior

Nothing should change from the older HOC version.

## Environment

- React InstantSearch Hooks version: 6.26.0
- React version: 17.0.2
- Browser: 103.0.5060.114
- OS: macOS

**Comment by Haroenv** [comment] 2022-07-20 08:31
do you have a sandbox with this behaviour? Have you tried the same code with the builtin `RangeInput` widget?

As a first hint, I'm not sure if you intended to write `attribute: category` or `attribute: "category"`?

**Comment by The-Code-Monkey** [comment] 2022-07-20 08:34
Problem is i can't allow access to our prod one, nor do i have the permissions to make an algolia index. Is there a test index that you guys have public that i can use?

**Comment by The-Code-Monkey** [comment] 2022-07-20 08:39
https://codesandbox.io/s/bold-napier-1vyn9b?file=/src/range-test.js

Here is an example of what i get when using your hooks sandbox.

**Comment by Haroenv** [comment] 2022-07-20 08:55
in your sandbox I get a `range` value of `1, 5000` though, however there's two initial renders where there's no refinement yet. You can see how we convert to a "inclusive range" in the e-commerce example: https://github.com/algolia/react-instantsearch/blob/580cbab8176e41719f423efeb620df5fce2e866b/examples/hooks-e-commerce/components/PriceSlider.tsx#L61-L71

**Comment by The-Code-Monkey** [comment] 2022-07-20 09:02
Ok but the other problem, as i think ive fixed that one is the fact that canRefine comes back as false which stops the refine function from working when previously it worked fine with the HOC version. What would cause the hook to say its not refineable.

**Comment by francoischalifour** [comment] 2022-07-20 11:41
This may be a bug because we need to add a check based on `results.__isArtificial` in `connectRange()`: https://github.com/algolia/instantsearch.js/blob/cf738b50d36c99c12995c79157920748094b4a7c/src/connectors/range/connectRange.ts#L428-L438

**Comment by Haroenv** [comment] 2022-07-20 12:44
based on `https://-3.algolianet.com/`, I see that you didn't pass any application id to `algoliasearch` (or possibly empty string)

**Comment by The-Code-Monkey** [comment] 2022-07-20 13:35
I thought that, but i have the 

appId, apiKey, and indexName all in the correct places if im correct.

So the algoliaSearch function takes the appId and the apiKey and then the InstantSearch component takes the indexName and the returned searchClient from the previous function. shouldnt be anything else i need to do correct?

**Comment by The-Code-Monkey** [comment] 2022-07-20 13:35
I will try manually putting them in rather than waiting for the api to pull it from our db

**Comment by The-Code-Monkey** [comment] 2022-07-20 13:37
Yeah i get the same results. Are there any config differences i need to make to the algolia index to enable the hooks to work or should they work the same

**Comment by Haroenv** [comment] 2022-07-20 13:44
It should work the same, but if you have a reproduction, that would be ideal, as there's something which is preventing the network request in your case, according to the stack trace

**Comment by The-Code-Monkey** [comment] 2022-07-20 14:20
> This may be a bug because we need to add a check based on `results.__isArtificial` in `connectRange()`: https://github.com/algolia/instantsearch.js/blob/cf738b50d36c99c12995c79157920748094b4a7c/src/connectors/range/connectRange.ts#L428-L438

Im guessing its due this comment as I can't think of any other reason why this wouldn't work?

**Comment by The-Code-Monkey** [comment] 2022-07-20 14:21
As if thats the only difference between the connectRange and useRange that would be my first point of call.

**Comment by The-Code-Monkey** [comment] 2022-07-20 14:36
@Haroenv 

I have found one thing by changing branch and going back to connectRange the currentRefinement comes back as undefined, undefined for min and max.

whereas the min and max for the useRange hook come back as 0 0 could that be the difference which is causing the canRefine value to be set to false instead.

**Comment by The-Code-Monkey** [comment] 2022-07-20 14:38
something else i just noticed even though we can refine is connectRange, canRefine is still false but allows the refine function to work thus allowing the range to work.

**Comment by The-Code-Monkey** [comment] 2022-07-21 09:24
I have just booted up a new project and im getting the same results with only the algolia lib installed and nothing else. I'm assuming its a config issue with our index.

If i want to use the useRange hook where do i need to put the key in the algolia index config.

**Comment by janmiofsky** [comment] 2022-07-26 13:42
@The-Code-Monkey  I think I have/had a similiar issue when moving from react-instant-search to react-instant-search hooks. 

After adding the attribute I wanted to use the range filter on to the Facets as not searchable I get results back from it. But it is still buggy. I work with timestamps and I can't work with future dates anymore, whereas this worked with the react-instant-search without any problems.

**Comment by dhayab** [comment] 2022-07-27 09:24
Hi, I've put React InstantSearch's `connectRange` and React InstantSearch Hooks `useRange` side by side, and `canRefine` is true after initial rendering, with the sample dataset from Algolia: https://codesandbox.io/s/small-sky-mrdflm?file=/src/ReactInstantSearch.js.

As React InstantSearch Hooks uses a different logic from React InstantSearch, the underlying API's can be incompatible. My guess is that your dataset configuration might miss something to make it work with React InstantSearch Hooks. For example, make sure your attribute is set as `attributesForFaceting` and that all the values are numbers, as stated here: https://www.algolia.com/doc/api-reference/widgets/range-input/react-hooks/?client=react#about.

**Comment by anandtoshniwal** [comment] 2022-11-26 11:42
Am getting below as a response while using useRange hook.

![Desktop-screenshot (4)](https://user-images.githubusercontent.com/15143023/204086924-3ee1943f-97a0-404c-a47f-eb0a964c4762.png)

**Comment by Haroenv** [comment] 2022-11-28 08:42
@anandtoshniwal what do you mean that you don't get results? range has a value, and start isn't set yet as it's not currently refined

**Comment by FabienMotte** [comment] 2022-12-21 15:37
@The-Code-Monkey Did @dhayab's answer help you out?

We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately and is to be mostly solved, so we're going to close it. Feel free to reopen it if needed.

**Closed by FabienMotte** 2022-12-21 15:37 UTC
Labels: fabien
