### ISSUE TITLE
Rendering delayed with slow network

### ISSUE THREAD

**Issue by rtman** [algolia/react-instantsearch#896] opened 2018-01-23 17:41 UTC
Hello,

While searching I'm noticing quite the slowdown for both highlighting and the correct results appearing. It seems like the second index is also quite a bit slower than the first. This doesn't seem to be the case in your storybook examples, I'm wondering if I'm doing something wrong? Are there guidelines for optimizing speed and responsiveness? 

EDIT* - This is with the dev setting off and no debugger session, production build.

![search_performance_mod_optimised](https://user-images.githubusercontent.com/20849135/35291084-821b38ec-006c-11e8-8d25-893a561d9b01.gif)

Code:
```
          <InstantSearch
            appId={algoliaAppId}
            apiKey={algoliaApiKey}
            indexName={this.props.indexName}
            onSearchStateChange={(searchState) => this.setState({searchQuery: searchState.query})}
            root={{
              Root: View,
              props: {
                style: {
                  flex: 1
                }
              }
            }}>
            <SearchBox/>
              <View style={{flex:1 }}>
                <ScrollView>
                  <SimpleHitsConnected 
                    header="Tags"
                    fieldOne="tag"
                    navigation={this.props.navigation}
                    onPressHit={this.onPressTag}
                    searchQuery={this.state.searchQuery}/>
                  <Index indexName="items">
                    <SimpleHitsConnected 
                      header="Items"
                      fieldOne="itemName"
                      navigation={this.props.navigation}
                      onPressHit={this.onPressItem}
                      searchQuery={this.state.searchQuery}/>
                  </Index>
                </ScrollView>
              </View>
          </InstantSearch>
```
I can provide all the code for my widgets and what not if you need, just didnt want to post a ton of code all at once.

Thanks

**Comment by Haroenv** [comment] 2018-01-24 13:06
I think a complete running example (for example in Expo) will be very useful here, the cause can be on a lot of places. I can't see any obvious foot guns here, so we'll need to investigate what the root cause is (the app or the library)

**Comment by rtman** [comment] 2018-01-24 15:44
Ok I think that is needed too, however I cannot share a complete running example publicly. Perhaps we can discuss this privately and come up with a way that I can share a running example for debugging. Then we could post the solution here for future reference.

**Comment by Haroenv** [comment] 2018-01-24 16:09
Yep, please send an email to support@algolia.com

**Comment by samouss** [comment] 2018-02-01 08:22
Close in favour of #465.

**Comment by samouss** [comment] 2018-02-02 12:00
My bad, I mixed the issue 😔  It's not the same as #465. The problem came from the fact that with a slow network we don't defer or cancel the rendering. When the lib will trigger 5 requests all of them are queued until they complete. It means that when they complete with an interval of time the rendering is also delayed. That's why we have the bahaviour observe in the picutre above.

We may found a solution for this, but it requires that the PR https://github.com/algolia/react-instantsearch/pull/933 is merged & released. If the solution is working, we will post an example.

**Comment by rtman** [comment] 2018-02-05 18:35
sounds good I will keep tracking this.

**Comment by samouss** [comment] 2018-02-06 15:09
Hi @rtman,

We found a solution that takes leverage of the `isSearchStalled` indicator. You can access this information through the connector `connectStateResults`. It's available in the latest version of React InstantSearch (at least v4.5.0). You can find more informations regarding this indicator in [our documentation](https://community.algolia.com/react-instantsearch/connectors/connectStateResults.html).

The workaround consist to look at the `nextProps` in the lifecycle `componentWillReceiveProps`. When the search is not stalled we call `setState` with the next values in order to trigger a render. But when the flag is `true` we keep the previous state as it is to prevent the component to trigger a new render. By doing this the results won't be updated until the "fresh" results are available.

Here is an example [on CodeSandbox](https://codesandbox.io/s/ov63q23n1y), it's easier to see the difference with a network throttling. On the first example the component we don't prevent the render when the search is stalled so as soon as the results arrive a new render is triggered. But on the second example we prevent the render when the search is stalled.

Let me know if it works for your use case.

```jsx
class AutoComplete extends Component {
  state = {
    hits: this.props.hits,
  };

  componentWillReceiveProps(nextProps) {
    if (!nextProps.isSearchStalled) {
      this.setState({
        hits: nextProps.hits,
      });
    }
  }

  render() {
    const { currentRefinement, refine, isSearchStalled } = this.props;
    const { hits } = this.state;

    return (
      <div>
        <input
          onChange={event => refine(event.currentTarget.value)}
          placeholder="Type your tags..."
          value={currentRefinement}
        />
        {currentRefinement && (
          <ul>
            {hits.map(suggestion => (
              <li key={suggestion.objectID}>
                <Highlight attributeName="name" hit={suggestion} />
              </li>
            ))}
          </ul>
        )}
      </div>
    );
  }
}

const AutoCompleteConnected = connectAutoComplete(connectStateResults(AutoComplete));
```

**Comment by rtman** [comment] 2018-02-17 14:46
@samouss 

Hey I'm just playing around with this now. keep in mind I'm still working with significant delay.

It seems like what this does is not show you updated hits until `isSearchStalled` is false, correct? So in use it makes the user think that their search is not working at all if there is significant delay.

Would a better idea be to show a loading spinner if its found that there is a certain amount of delay? How does `isSearchStalled` work exactly? The docs show `Flag that indicates if React InstantSearch has detected that searches are stalled.` Can you explain the criteria for determining if a search is stalled?

**Comment by samouss** [comment] 2018-02-18 09:11
Yes this is what it does, we do not show the results until `isSearchStalled` is `false`. Did you look at the [CodeSandbox](https://codesandbox.io/s/wqm12m7595) example? It does exactly what you describe. The autocomplete display a loader as soon as the search is stalled.

A search is declared "stalled" when there are still pending requests after a given delay. The default one is 200ms but it can be configured on the component [`<InstantSearch>`](https://community.algolia.com/react-instantsearch/widgets/%3CInstantSearch%3E.html#default-props-entry-<InstantSearch>-stalledSearchDelay).

**Comment by rtman** [comment] 2018-02-18 12:39
I see it now, it was occuring so fast and the spinner was a light grey so I didn't even notice it. 

I will try this out and see how it works for me, thanks.

**Comment by samouss** [comment] 2018-06-08 15:18
I'm closing this one since it's inactive, feel free to re-open an issue.

**Closed by samouss** 2018-06-08 15:18 UTC
Labels: Type:❔ Question

**Comment by hadesunseenn** [comment] 2021-11-24 17:36
did someone find solution for this ?
