### ISSUE TITLE
[react-instantsearch-hooks] Back button doesn't return to the correct state in certain situations in the remix example

### ISSUE THREAD

**Issue by wintersieck** [algolia/react-instantsearch#3580] opened 2022-07-27 18:26 UTC
## 🐛 Bug description

In the [remix example](https://github.com/algolia/react-instantsearch/blob/d50a5807eb8a9d82412fbdf39b52e939a68f19ee/examples/hooks-remix/app/routes/index.tsx), it doesn't seem that UI state is set correctly when initially loading the page, causing the back button to not work in some situations (see reproduction below).

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Run the [remix example](https://github.com/algolia/react-instantsearch/blob/d50a5807eb8a9d82412fbdf39b52e939a68f19ee/examples/hooks-remix/app/routes/index.tsx).
2. Click on `Insignia™` to filter (any filter will work).
3. Reload the page.
4. Click on `Samsung` to filter again (any additional filter will work).
5. Click back.

It should return to just `Insignia™` filtered, but instead returns to no filters at all.

One thing we noticed: if you check `history.state` in the console after reloading the page in step 3, it doesn't have `uiState` in there (it has something else instead), which I think causes the issue when returning to this history state in step 5.

## 💭 Expected behavior

Back and forward buttons return to the correct state.

## Environment

- React InstantSearch Hooks version: 6.30.2
- React version: 18.1.0
- Browser: Chrome Version 103.0.5060.114
- OS: Windows

## Additional context

Thank you for your work!

**Comment by wintersieck** [comment] 2022-07-27 18:34
This is likely the same underlying bug, but in our app, we have a `null` value in the initial `history.state` which causes an error when clicking back instead of just losing state. It's difficult to provide a minimal reproduction for this given the custom `history.state`, but you can simulate the issue with this flow:

1. Run the [remix example](https://github.com/algolia/react-instantsearch/blob/d50a5807eb8a9d82412fbdf39b52e939a68f19ee/examples/hooks-remix/app/routes/index.tsx).
2. Run `history.replaceState({test: null}, "test");` in the console to simulate having a `null` value in state. Note that we're not overwriting `uiState` with this, because `uiState` isn't in `history.state` at this point (which is probably the underlying bug?). You can see what I mean by checking `history.state` in the console before running `history.replaceState({test: null}, "test");`.
3. Click on `Insignia™` to filter (any filter will work).
4. Click back.

You'll get `Uncaught TypeError: Cannot read properties of null (reading 'configure')` when it tries to parse the `null` in `history.state`.

Pretty sure the underlying issue is that `history.state` should get replaced with `uiState` on initial load, which would fix both this scenario and the original issue.

Thank you!

**Comment by AryanJ-NYC** [comment] 2022-08-01 17:10
Dupe of #3506, point 2.

**Comment by FabienMotte** [comment] 2022-12-21 15:45
We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js).

This should be fixed by https://github.com/algolia/instantsearch.js/pull/5177 in the next release, feel free to reopen if needed.

**Closed by FabienMotte** 2022-12-21 15:45 UTC
Labels: fabien
