### ISSUE TITLE
Flicker due to outdated results

### ISSUE THREAD

**Issue by oyeanuj** [algolia/react-instantsearch#704] opened 2017-12-08 21:03 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When I type in the first character, it flickers for a second due to the unrelated results being in the `hits` array. 

If I type in a character, and remove it, and type in another one, you'll notice the same flash of outdated results (FOUR?).

![autocompleteflicker](https://user-images.githubusercontent.com/9633371/33784962-cdd969bc-dc17-11e7-8797-ef5ab2427b80.gif)

**Bug: What is the expected behavior?**
`hits` shouldn't have results when there is no `currentRefinement` or once the `currentRefinement` is deleted to an empty string, then `hits` should reset.

FWIW, I am using the `connectAutoComplete` connector.

**Comment by samouss** [comment] 2017-12-08 21:59
Closing this one, because duplicate of #465.

**Closed by samouss** 2017-12-08 21:59 UTC
Labels: Type: ❤️ Bug
