### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by m-vdb** [algolia/react-instantsearch#609] opened 2017-11-14 14:18 UTC
**Env**: react-native + jest (during test run)
**Version**: 4.2.0 (latest)

**Bug: Current behavior**

When running `jest` I get the following error:
```javascript
ReferenceError: window is not defined
      
      at Object.<anonymous> (node_modules/algoliasearch/src/reactnative/builds/algoliasearch.reactnative.js:9:13)
      at Object.<anonymous> (node_modules/algoliasearch/reactnative.js:4:16)
      at Object.<anonymous> (node_modules/react-instantsearch/native.js:17:18)
```

**Bug: Expected behavior**

Use `global` instead [here](https://github.com/algolia/algoliasearch-client-javascript/blob/master/src/reactnative/builds/algoliasearch.reactnative.js).

**How to reproduce**

```bash
$ git clone git@github.com:m-vdb/algolia-window-issue.git
$ cd algolia-window-issue
$ node --version
v6.11.2
$ npm install .
$ npm test
> algolia-with-issue@0.0.1 test /Users/mvdb/algolia-window-issue
> jest __tests__/

 FAIL  __tests__/super.spec.js
  ● Test suite failed to run

    ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/algoliasearch/src/reactnative/builds/algoliasearch.reactnative.js:9:27)
      at Object.<anonymous> (node_modules/algoliasearch/reactnative.js:4:16)
      at Object.<anonymous> (node_modules/react-instantsearch/native.js:17:18)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        24.297s
Ran all test suites matching /__tests__\//i.
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |        0 |      100 |        0 |        0 |                |
 index.js |        0 |      100 |        0 |        0 |              2 |
----------|----------|----------|----------|----------|----------------|
npm ERR! Test failed.  See above for more details.
```

**Comment by Haroenv** [comment] 2017-11-14 14:51
Thanks for opening this issue, could you quickly make a repository with this behaviour? We have RN tests with Jest without problem 🤔

**Comment by m-vdb** [comment] 2017-11-14 16:46
there you go @Haroenv I've updated the desc

**Comment by vvo** [comment] 2017-11-16 14:00
This is linked to the JavaScript client, I bet when running tests with Jest, if you are in the node env instead of jsdom this trigger that

**Comment by Haroenv** [comment] 2017-11-16 14:15
I don't think that's the cause @vvo, since the default is `jsdom` and there's no other env specified in https://github.com/m-vdb/algolia-window-issue/blob/master/package.json#L42-L66

**Comment by samouss** [comment] 2017-11-16 16:29
Actually I think the issue is related to the new version of React Native. In a React Native environment `window` is defined by the framework. You can find this declaration in [`InitializeCore`](https://github.com/facebook/react-native/blob/master/Libraries/Core/InitializeCore.js#L36). But they recently made a change in the Jest `setup` file. They now mock by default the file `InitializeCore` (you can see the line [here](https://github.com/facebook/react-native/blob/master/jest/setup.js#L37)), so the file is not loaded anymore in the test environment.

That's why the `window` object is not defined in the Jest environment.

**Comment by samouss** [comment] 2017-11-16 17:02
As a workaround you can define `window` in your `setup` file. It makes more sense to define it rather than using `global` in the client, because `window` is defined in the React Native environment.

You can take example on the `expo-preset`.

https://github.com/expo/jest-expo/blob/master/src/setup.js#L17

**Comment by m-vdb** [comment] 2017-11-16 22:10
that's exactly what I did to circumvent the problem but I don't think it's an acceptable long-term solution. I don't think that window should be used for RN code. I don't know what's the community thoughts though, what do you think?

**Comment by Haroenv** [comment] 2017-11-17 07:33
Window is defined in RN code for some globals

**Comment by samouss** [comment] 2017-11-17 10:35
I'm closing this one since we have a workaround. Feel free to reopen if you feel this isn't sufficient 😉

**Closed by samouss** 2017-11-17 10:35 UTC
Labels: Type:❔ Question, ⭐️ Needs investigation

**Comment by vUdav** [comment] 2019-07-12 17:00
I'm use this config on my `package.json` and it's help for me

```json
"jest": {
  "globals": {
    "window": true
  }
}
```

**Comment by Haroenv** [comment] 2019-07-13 13:55
could you make a reproducible example @vUdav ?
