### ISSUE TITLE
Components should not fire searchStateChanged on unmount

### ISSUE THREAD

**Issue by ajsharp** [algolia/react-instantsearch#2429] opened 2019-05-13 07:18 UTC
**Describe the bug 🐛**

This issue has been documented in other tickets, notably #302.

Many components and component connectors fire a searchStateChanged event when they unmount, which makes it very difficult to do routing properly. You end up needing a bunch of brittle conditional code in your onSearchStateChanged handler to make sure you're not repeatedly pushing the same url onto the history object because the onSearchStateChanged gets called for _every_ component that unmounts.

In #302, there is some discussion that argues that the event should be fired because an unmount indicates that the searchState _must've changed_ -- but this is not deterministic and very buggy:

https://github.com/algolia/react-instantsearch/issues/302#issuecomment-326892417
> It's expected that every time a component is unmounted onSearchStateChange get called because it means that a new request has been made => some filters could have change, etc.

I see the point, but it's not clear why this should necessitate an event being fired for _every_ mounted component, or at all. Shouldn't the event just be fired by the component that initiated the state change directly?

## Example

Assume you have an app with a Searchbox, a pagination widget, a refinement list and a current refinements component. If you link from a search screen to a detail screen, the search state changed handler will get fired several times. This sandbox illustrates the problem (watch the console log): https://codesandbox.io/s/8z0n8p0py2

**Environment:**

 - Browser: all
 - Version: 5.5.0

**Comment by Haroenv** [comment] 2019-05-13 07:20
Could you not memoize your routing function so if it still calculates the URL multiple times, but it will only push where necessary?

**Comment by samouss** [comment] 2019-05-13 15:04
I've answer your comment inside the https://github.com/algolia/react-instantsearch/issues/302#issuecomment-491857307 thread. For the example you gave, indeed the callback is called multiple times. This is expected: you have 3 widgets with a cleanup method which means that `onSearchStateChange` is called three times. For this example in particular you don't have to wrap the full application with the `InstantSearch` component. The only component that have to be aware of the search is `App` not the `RootApp` neither `Detail`. With this change the callback is not triggered when the page change because the provider is also unmounted. Here is [the example](https://codesandbox.io/s/z65v5rr0z4) updated with the approach I've described.

**Comment by ajsharp** [comment] 2019-05-13 16:22
@Haroenv I've tried, but the logic is proving extremely complex and brittle, and I haven't been able to get it to work yet.

@samouss I understand that the library works that way, and that it's expected behavior. My argument is that it shouldn't -- that seems like a bug to me. If the PaginationList component or the CurrentRefinements component are triggering an event that's linked to the url changing when their state is not actually changing, that seems like a bug.

I have my `<InstantSearch />` component high up in tree because I need it to wrap most of my app. Sometimes I show a search box in the nav bar, but sometimes it's shown in the page body. Thus, I need it high up. If there's another solution, I'm open to it.

**Comment by ajsharp** [comment] 2019-05-13 16:29
Also, a simple way to allow the user to opt-out of this behavior would be to pass `isUnmounting` in a second argument to the `onSearchStateChanged` function.

**Comment by ajsharp** [comment] 2019-05-14 16:46
For anyone else coming across this issue, the workaround I found was to localize the `InstantSearch` components as close to the components using them as possible. Previously, I had one InstantSearch component that effectively wrapped my app and my react router `Route` components, which I think was causing the unmount behavior. By keeping them inside the routes, I think everything gets unmounted at once, so the issue described above is not encountered.

It might be worth adding something to the instantsearch documentation pointing out this issue.

**Comment by samouss** [comment] 2019-05-15 11:08
@ajsharp For the use case with the `SearchBox` inside the header, React provides a built-in primitive for that: [Portal](https://reactjs.org/docs/portals.html). The `context` exposed by the Provider is also provided to the Portal which makes a perfect fit for the use case.

The solution you came up with is the correct approach with our current implementation. The widget driven UI is intuitive for 80% of the cases but we are aware that it's not the best approach for all use cases. It's definitely something that we want to tackle at some point, but we don't have the bandwidth to do it at the moment. I'm closing the issue since it's a duplicate of #302 and it's not something we're gonna address soon.

**Closed by samouss** 2019-05-15 11:08 UTC
