### ISSUE TITLE
connectRange "currentRefinements" from getProvidedProps is not aligned with getMetadata

### ISSUE THREAD

**Issue by rtman** [algolia/react-instantsearch#920] opened 2018-01-29 10:27 UTC
I'm using a Multi Slider in connectRange with auto computed max and min range. When I adjust the slider markers it is reflected in my currentRefinement widget. The issue is that if I leave either slider marker at the autoComputed max or min, that value shows up as undefined. Otherwise values show up as they should. I've traced it through console log and the refine() function is passed the correct max or min value, but when it shows up in currentRefinements its undefined, but only if its the max or min value. Any ideas?

Console log:

![max min undefined](https://user-images.githubusercontent.com/20849135/35505480-851d784c-04e6-11e8-9213-7802c21939bf.PNG)

Here's my code:

```
export const CurrentRefinements = connectCurrentRefinements(({ refine, items }) => {
  console.log('CurrentRefinements items', items);
  return(
    <View style={items.length === 0 ? null : {padding:8}}>
      <FlatList
        data={items}
        horizontal
        keyExtractor={(item, index) => item.objectID}
        renderItem={({ item }) => {
          const RenderRefinement = (() => {
              var renderString = ''
              switch(item.attributeName) {
                case 'categories.lv0':
                  renderString = `Category: ${item.currentRefinement}`              
                  break;
                case 'companyName':
                  renderString = `Company: ${item.currentRefinement}`
                  break;
                case 'price':
                  renderString = `Price: ${item.currentRefinement.min} - ${item.currentRefinement.max}`
                  break;
              return(
                renderString
              ) 
          })
          return (
            <View style={{padding: 8}}>
              <TouchableOpacity
                style={{backgroundColor: Colors.secondaryColor, padding: 6}}
                onPress={() => {
                  refine(item.value);
                }}
              >
                <View style={{alignItems: 'center', justifyContent: 'center', flexDirection: 'row'}}>
                  <Text style={{color: Colors.primaryGrayColor}}>
                    <RenderRefinement/>
                  </Text>
                  <Icon style={{paddingLeft: 2}} name={'close'} size={20} color={Colors.primaryGrayColor}/>
                </View>
              </TouchableOpacity>
            </View>
          );
        }}
      />
    </View>
  )
})


export const DrawerRangeMultiSlider = connectRange(({refine, currentRefinement, header, min, max}) => {
  return(
    <RangeMultiSlider refine={refine} currentRefinement={currentRefinement} header={header} min={min} max={max}/>
  )
})

export class RangeMultiSlider extends React.Component{
  constructor(props){
    super(props);
    this.state = {
      sliderValues: {
        min: this.props.min, 
        max: this.props.max
      },
      sliderRange: {
        min: this.props.min,
        max: this.props.max
      },
      markersEnabled: true,
    }; 
  }

  round(value, decimals) {
    return Number(Math.round(value+'e'+decimals)+'e-'+decimals);
  }

  onChangeValues = (values) => {
    this.setState({
      sliderValues: {
        min: this.round(values[0],2),
        max: this.round(values[1],2)
      }
    }, console.log(this.props.header,' this.state.sliderValues', this.state.sliderValues))
  }

  componentWillReceiveProps(nextProps){

    if(nextProps.min === nextProps.max){
      this.setState({
        markersEnabled: false,
      })
    } else if (nextProps.min !== nextProps.max && this.state.markersEnabled === false){
      this.setState({
        markersEnabled: true,
      })      
    }

    if(this.state.sliderValues.min !== nextProps.currentRefinement.min || this.state.sliderValues.max !== nextProps.currentRefinement.max){
      this.setState({
        sliderValues: {
          min: nextProps.currentRefinement.min, 
          max: nextProps.currentRefinement.max
        },
      })
    }
    if(this.state.sliderRange.min !== nextProps.min || this.state.sliderRange.max !== nextProps.max){
      this.setState({
        sliderRange: {
          min: nextProps.min,
          max: nextProps.max
        }
      })
    }
  }

  onChangeValuesFinish() {
    if (this.props.currentRefinement.min !== this.state.sliderValues.min || this.props.currentRefinement.max !== this.state.sliderValues.max) {
      console.log(this.props.header,' onChangeValuesFinish this.state.sliderValues',this.state.sliderValues)
      this.props.refine({
        min: this.state.sliderValues.min, 
        max: this.state.sliderValues.max
      });
    }    
  }

  render(){
    return(
    <View style={{padding:8}}>
      <Text style={{paddingLeft: 10, fontSize: 14, color: Colors.primaryTextColor, alignSelf: 'flex-start' , textAlign: 'left'}}>
        {`${this.props.header}:`}
      </Text>
      <View style={{paddingTop: 20, paddingLeft: 8}}>
        <MultiSlider
          sliderLength={150}
          containerStyle={{height:10}}
          onValuesChange={(sliderState) => this.onChangeValues(sliderState)}
          min={this.state.sliderRange.min}
          max={this.state.sliderRange.max}
          onValuesChangeFinish={() => this.onChangeValuesFinish()}
          values={[this.state.sliderValues.min, this.state.sliderValues.max]}
          step={1}/>
      </View>
      <View style={{flexDirection: 'row', justifyContent: 'space-between'}}>
        <Text style={{fontSize: 14, color: Colors.primaryTextColor, textAlign: 'left'}}>
          {this.state.sliderValues.min}
        </Text>
        <Text style={{fontSize: 14, color: Colors.primaryTextColor , textAlign: 'right'}}>
          {this.state.sliderValues.max}
        </Text>
      </View>
    </View>
    )
  }
}
```

**Comment by samouss** [comment] 2018-01-29 11:50
Yes this is the intended behaviour. Inside the `connectCurrentRefinements` you get the raw values of the actual refinement. When you don't provide a `min` or `max` the values are computed from that Algolia results. When the slider is at the bounds of the range, we consider that the `currentRefinement` is `undefined` since the values are equal to the current `min` or `max`. When you refine the results with those values it doesn't make sense to apply the filters since it's the complete range available.

The behaviour differ from the one with the props provided by `connectRange`. In the latter we "normalize" the `currentRefinements` with the value of the range. But we are doing this in order to be backward compatible. This behaviour should change in the upcoming version in order to align it with `connectCurrentRefinements`. The connector should send the raw values and the component is responsible for displaying the correct one. It's more flexible to have the raw results instead of the "normalize" version IMO.

cc @Haroenv @vvo

**Comment by rtman** [comment] 2018-01-29 12:53
> When the slider is at the bounds of the range, we consider that the currentRefinement is undefined since the values are equal to the current min or max. When you refine the results with those values it doesn't make sense to apply the filters since it's the complete range available.

This is true but the situation that I'm specifically talking about is when using a multi slider (slider with 2 markers) and when only one of the bounds is at the max or min, then you are applying a filter and showing one of the values as undefined since it is at the max or min.

Is there no temporary workaround until this is fixed ?

**Comment by samouss** [comment] 2018-01-29 12:59
I saw that on your component you are using the `currentRefinement` for build a label.  But there is also a `label` property available on item and it should be correct. I agree that it's not the same shape as yours but it could be a workaround. Did you try it?

```js
case 'price':
  renderString = `Price: ${item.currentRefinement.min} - ${item.currentRefinement.max}`
break;
```

**Comment by rtman** [comment] 2018-01-29 13:56
The about that is while it doesn't show undefined, it will not show max min number either. For price it shows ' Price =< 5', and that's not super helpful as I don't know what the bottom end of the range is there.

**Comment by samouss** [comment] 2018-01-29 16:11
This is the path that we have take for displaying the refinement inside the `CurrentRefinement` widget. We don't show value where there is no refinement apply on it.

**Comment by rtman** [comment] 2018-01-29 16:22
> We don't show value where there is no refinement apply on it.

But there is a refinement to apply here. Lets say min and max are autoComputed to be 1 and 5 respectively. If the slider is set to 1 and 5 then yes there is no refinement to apply as you are showing all values. But if you move one end and change it to 1 and 3, there is a refinement to apply. The refinement is values >= 1 and <= 3.

The user has no idea what the range is, so you have to show the lower and upper bounds of the refinement or else they won't understand what they looking at. If the label just shows <=3 it could be 0 to 3, 1 to 3, 2 to 3, 2.5 to 3... and so on. Right?

**Comment by samouss** [comment] 2018-01-29 16:35
In your example when you move the slider the refinement is *from* everything *to* 3, since you didn't set the minimum value. When the minimum value is equal to the minimum of the range we don't consider that a refinement is applied. The label `price <= 500` means that the results will be under 500 without informations about the minimum since no minimum is set.

The behaviour has the intent to be extendable, we provide the raw values in order to build your own label. When the issue will be fixed you will be able to set you own label.

**Comment by rtman** [comment] 2018-01-29 16:38
Alright, I guess I'll just follow this issue and see what you guys come up with. Thanks for looking into it.

**Closed** 2018-02-05 11:45 UTC
Labels: Type: ❤️ Bug, ♨ API

**Comment by rtman** [comment] 2018-02-17 13:33
Thanks the fix works great.
