### ISSUE TITLE
[react-instantsearch-hooks] Next.js Back button broken once facets applied

### ISSUE THREAD

**Issue by daxupaxu** [algolia/react-instantsearch#3593] opened 2022-08-04 12:28 UTC
## 🐛 Bug description

Known issue with keeping in sync NextJS Router with Algolia Router
- Page doesn't loads at all when navigating by using browser back button from the NextJS page into page with `InstantSearchSSRProvider` until page refresh

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to `https://codesandbox.io/s/vibrant-hellman-ipc0vx`
2. Select couple facets
3. Click on `contact page` link on the top
4. Click back button in the browser
6. See error

**Live reproduction:**

https://codesandbox.io/s/vibrant-hellman-ipc0vx

## 💭 Expected behavior

Once back button page is clicked it should load the page with facets applied based upon the url

## Environment

- React InstantSearch Hooks version: 6.31.0
- React version: 18.1.0

**Comment by dhayab** [comment] 2022-08-04 15:23
Hi, thanks for your feedback.

This is a duplicate of https://github.com/algolia/react-instantsearch/issues/3506 (point 2 more precisely). I'll close this issue as such, but feel free to follow https://github.com/algolia/react-instantsearch/issues/3506 for a possible workaround while we work on revamping our routing mechanism to prevent conflicts with third-party routing.

**Closed by dhayab** 2022-08-04 15:23 UTC
