### ISSUE TITLE
Range on multiple attributes

### ISSUE THREAD

**Issue by andreyvital** [algolia/react-instantsearch#2830] opened 2019-09-16 13:54 UTC
**Is your feature request related to a problem? Please describe 🙏**

No.

**Describe the solution you'd like 🤔**

I want to be able to filter a range between two attributes. Say that I have two properties in my document: `quantityA` and `quantityB` and I want to filter if they're between range `0 TO 100`.

The query would translate to:
```
(quantityA:0 TO 100) OR (quantityB:0 TO 100)
```

This could be done through `numericFilters`: https://www.algolia.com/doc/api-reference/api-parameters/numericFilters/#examples.

I am not sure how to use existing connectors to do that, I have considered writing a new one but I am not sure where to start. I was trying to `setQueryParameter("numericFilters", [...])` and it actually works, but I can't seem to figure out how to get the filter cleared by `<ClearFilters />` if the user wants to.

Any thoughts?

**Comment by Haroenv** [comment] 2019-09-16 13:59
What would this visually look like? All widgets on a page usually (in our case always) have the convention of "refining more", and thus being "AND" between them, unless in a single widget

**Comment by andreyvital** [comment] 2019-09-16 14:02
So it's a single range slider that needs to take into account two properties. A single range slider will match quantityA or B with the same selected range.

**Comment by Haroenv** [comment] 2019-09-16 15:36
This is not something we have by default; but we have this connector that likely solves most of your use case, it would be nice to hear if it solves your use-case, so we can think about incorporating it in the library: https://codesandbox.io/s/kwklo3rz63

**Comment by Haroenv** [comment] 2019-12-03 15:06
I just noticed this is a duplicate of #91, so I'll close this

**Closed by Haroenv** 2019-12-03 15:06 UTC
