### ISSUE TITLE
Always trigger search when mounting

### ISSUE THREAD

**Issue by vinhlh** [algolia/react-instantsearch#376] opened 2017-09-25 16:11 UTC
If having a `Configure` element, `react-instantsearch` will trigger a request when mouting, depsite we don't do any thing with search feature yet.

```js
<InstantSearch appId={appId} apiKey={apiKey} indexName={indexName}>
    <Configure {...configureAlgolia()} />
  </InstantSearch>
```

**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
A redundant request
<img width="905" alt="screen shot 2017-09-26 at 12 08 18 am" src="https://user-images.githubusercontent.com/261283/30818775-1968e77a-a24f-11e7-8657-b5d2d5b2ddca.png">

**Bug: What is the expected behavior?**
Should not have

**Bug: What browsers are impacted? Which versions?**
Chrome 60

**What is the version you are using? Always use the latest one before opening a bug issue.**
4.1.1

**Comment by mthuret** [comment] 2017-09-25 16:16
Hi @vinhlh,

As for now there's no API to disable the first query but that's something on the RIS backlog to consider. 

I'd prefer to go for this kind of API than coding a particular use-case. (ie: when only Configure type widget, do not search). But let's discuss about it!

**Comment by oyeanuj** [comment] 2017-12-03 23:34
@mthuret Also came here to report the same issue. Is there a way to disable that extra search query (unless it is needed by the widget)? Or is that the API you were thinking of adding?

FWIW, apart from extra operation, it makes debugging initially confusing.

**Comment by Haroenv** [comment] 2017-12-04 09:07
@oyeanuj, in most search UIs you'll want the first launch to have the results for an empty query, which can be used for browsing. In autocomplete cases you can show or hide the results based on how long the query is. 

The API Marie was thinking of was indeed something to prevent a search request from firing on a condition that you decide. 

In practice this one extra request shouldn't affect you too much, since in the worst case, it'll simply warm up your DNS cache for the real requests

**Comment by oyeanuj** [comment] 2017-12-05 19:52
@Haroenv Got it, thanks for the context.

**Comment by samouss** [comment] 2018-08-21 07:46
Duplicate of https://github.com/algolia/react-instantsearch/issues/1111

**Closed by samouss** 2018-08-21 07:46 UTC
Labels: ♨ API
