### ISSUE TITLE
result list with hits get reset when component with “useSortBy” hooks is closed

### ISSUE THREAD

**Issue by rosnk** [algolia/react-instantsearch#3635] opened 2022-09-24 12:17 UTC
I am using "import { useSortBy } from "react-instantsearch-hooks", to create a sortby dropdown in expo project(react native). This sort by component is inside parent component, which opens like model.

Problem: sorting works fine while i open the filter component and choose different filter(ex by price desc, price asc), but as soon as i close the model, whole shorted list result is reset... basically result does not stick to the my choosen sorted result.

video: https://youtu.be/J5uZF01lVtU

pic1: before any sorting, results are as in pic:

pic2: i click the filter, which shows component similar to model, where i can choose dropdown filter, results after i click desc(which is working fine while, filter screen is still showing):

pic3: once i click the filter icon to remove the filter screen, result does not stick to price by desc, it resets to original result:

here is the source code in snack: https://snack.expo.dev/@rosnk/algoli_sortby_example_buggy

note: ( snack code is perfectly fine.... snack is showing error on import line of algolia... that is on this line: import { InstantSearch } from "react-instantsearch-hooks";

**Comment by FabienMotte** [comment] 2022-12-22 13:57
We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue is a duplicate of https://github.com/algolia/react-instantsearch/issues/3542 so we're going to close it.

Two possible workarounds are listed here: https://github.com/algolia/react-instantsearch/issues/3542#issuecomment-1170076834

**Closed by FabienMotte** 2022-12-22 13:57 UTC
Labels: fabien
