### ISSUE TITLE
Next.js SSR/SSG: React Instant Search Hooks makes app build HTML client-side (empty <div id="__next">)

### ISSUE THREAD

**Issue by danielkolbespecial** [algolia/react-instantsearch#3588] opened 2022-08-03 13:23 UTC
## 🐛 Bug description

When using the `<InstantSearch />` wrapper component in _app.js, the `<div id="__next">` is empty on the initial page load. Seems like the app is built on the client side when using Instant Search. I've tested this with Postman.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Add `<InstantSearch />` wrapper to _app.js in a Next.js application
2. Fetch site using Postman or CURL
3. Check content of `<div id="__next">` (it'll be empty)
4. Compare this to the same app that doesn't use `<InstantSearch />`

## 💭 Expected behavior

The full html should get generated on the server and then get rendered inside of `<div id="__next">`

## 🖥 Screenshots

<img width="1253" alt="algolia-postman" src="https://user-images.githubusercontent.com/14195521/182618308-a5f283e4-52ba-4b1e-8f05-1eeca6e96edd.png">

## Environment

- React InstantSearch Hooks version: 6.30.2
- React version: 18.1.0
- Next.js version: 12.2.0

**Comment by dhayab** [comment] 2022-08-03 15:58
Hi, `<InstantSearch>` by itself will not render HTML on SSR environment. You need to use `<InstantSearchSSRProvider>`, a wrapper dedicated to this use case and pass it the initial results.

You can check-out the [Server-Side Rendering with React InstantSearch Hooks](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/) guide for more information.

**Comment by danielkolbespecial** [comment] 2022-08-04 08:04
@dhayab Thank you very much! As far as I understand `<InstantSearchSSRProvider />` is only for SSR pages. In my case I try to use SSG with `getStaticProps`, which won't work with `<InstantSearchSSRProvider />`, right?

I have my search included on all pages in the header. Does that mean I can't use SSG when using Algolia?

**Comment by dhayab** [comment] 2022-08-04 08:31
Thanks for this valuable feedback. Indeed there is no direct mention of SSG, but `<InstantSearchSSRProvider>` is just a context provider for initial results destined to InstantSearch, no matter where they come from.

You can still follow the Next.js section of the SSR guide, but instead of retrieving the initial search results using [`getServerState()`](https://www.algolia.com/doc/api-reference/widgets/server-state/react-hooks/) in `getServerSideProps()`, you do it in `getStaticProps()`.

This should allow you to generate the static HTML at build time.

**Comment by bronsondunbar** [comment] 2022-08-04 08:41
Hi @dhayab, 

I am collaborating with @danielkolbespecial on this.

But `req` as per the example here: https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/#with-nextjs is not available in `getStaticProps()`?

Also if I move `<InstantSearch>` & `<InstantSearchSSRProvider>` to a page, I cannot seem to use the `useInstantSearch()` hook in the page anymore?

**Comment by dhayab** [comment] 2022-08-04 08:58
In the SSR guide, `req` is used to set up routing which will provide initial refinements. In your case you can't rely on routing so you'll have to find other means to provide initial refinements if you need them.

As for your second question, Hooks from React InstantSearch Hooks need to be called from within `<InstantSearch>` because they require access to the context it creates.

**Comment by bronsondunbar** [comment] 2022-08-04 09:18
@dhayab I am getting the following error event though I have imported and mounted the component.

`Error: Unable to retrieve InstantSearch's server state in `getServerState()`. Did you mount the <InstantSearch> component?`

**Comment by dhayab** [comment] 2022-08-04 09:42
Not sure how you would get this error. Could you reproduce it in a sandbox? You can use [this one](https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/hooks-next?file=/pages/index.tsx) as a template if you want.

**Comment by bronsondunbar** [comment] 2022-08-04 10:19
@dhayab I tried re-creating the example from here: https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/#with-nextjs

But I get an error in the sandbox? https://codesandbox.io/s/ancient-resonance-rqz1xr?file=/pages/index.js

**Comment by dhayab** [comment] 2022-08-10 17:42
Hi, I can't say why you have this issue, although you don't need to import the `history` router for static generation, as I mentionned earlier.

Here you'll find a sandbox implementing `getStaticProps()` that generates the HTML for the InstantSearch implementation during build time: https://codesandbox.io/s/react-instantsearch-3588-dgdgz4. You can check the source of the rendered page here: https://dgdgz4.sse.codesandbox.io/.

**Comment by FabienMotte** [comment] 2022-12-22 09:51
@bronsondunbar @danielkolbespecial Did @dhayab's answer help you out?

We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately and is to be mostly solved, so we're going to close it. Feel free to reopen it if needed.

**Closed by FabienMotte** 2022-12-22 09:51 UTC
Labels: fabien
