### ISSUE TITLE
Issue rendering Algolia search component on server

### ISSUE THREAD

**Issue by PVAngular** [algolia/react-instantsearch#3200] opened 2021-11-18 02:03 UTC
We use react-instantsearch-dom npm for search in our  website. Recently, we moved to server side and running into issues like the below - Can you help us fix this as this is totally blocking  our release?

```
Something went wrong: Cannot read properties of undefined (reading 'node') (req_id=c87c9418-b033-4c7e-9b5c-10aacb99db47, env=dev, intuit_tid=ssr-9ff7dff3-cfbd-48b5-ae21-2c4a22e4fe9c, versionTag=versionTag)
  webpack:///../developer-homepage-ui/node_modules/algoliasearch/src/server/builds/node.js?:73
  algoliasearch.ua = 'Algolia for JavaScript (' + algoliasearch.version + '); ' + 'Node.js (' + process.versions.node + ')';
```

**Comment by dhayab** [comment] 2021-11-18 10:28
`process.versions` should not be `undefined` if you're executing the code from a node environment. Could you provide a sandbox where this problem appears?

**Comment by tkrugg** [comment] 2021-11-18 12:35
It looks like to me you have a situation where some server-side code get bundled by webpack and served to the client.  I agree with @dhayab a codesandbox could help, or anything that helps replicate. It's most likely a configuration tweak inside webpack.

**Comment by tkrugg** [comment] 2021-11-19 16:11
Hey @PVAngular I'll close the issue for now, but feel free to reopen when you're able to help us reproduce. Happy to help you troubleshoot this.

**Closed by tkrugg** 2021-11-19 16:11 UTC
