### ISSUE TITLE
Use renderProps to render the components

### ISSUE THREAD

**Issue by clayne11** [algolia/react-instantsearch#1429] opened 2018-07-13 15:07 UTC
I propose that the library should use the render props pattern to display results. It has been gaining a lot of steam in the community and would allow for a much more customized rendering experience.

This library does a good job encapsulating all of the logic of performing searches but IMO is far too opinionated about rendering.

CSS-in-JS has taken off in the React community and a lot of projects do not use CSS classes. Additionally, there are so many options for styling components that it makes sense to keep `react-instantsearch` as the logic behind the search and to allow users to render the results however they want.

The current implementation of `react-instantsearch` can be created as a separate package, and the community is then free to implement new rendering methods of `react-instantsearch` while the library maintainers only need to focus on the Algolia logic.

It could look something like this:

```tsx
const App = ({ curValue }) => (
  <InstantSearch
    appId="latency"
    apiKey="6be0576ff61c053d5f9a3225e2a90f76"
    indexName="ikea"
  >
    <Configure hitsPerPage={1} />
    <Index indexName="bestbuy" />
    <Index indexName="airbnb" />
    <Hits>
      {({ hits, refine }) => (
        <Autosuggest
          suggestions={hits}
          multiSection={true}
          onSuggestionsFetchRequested={({ value }) => refine(value)}
          onSuggestionsClearRequested={this.onSuggestionsClearRequested}
          getSuggestionValue={this.getSuggestionValue}
          renderSuggestion={this.renderSuggestion}
          inputProps={{
            placeholder: 'Search for a product...',
            onChange: this.onChange,
            value: curValue,
          }}
          renderSectionTitle={this.renderSectionTitle}
          getSectionSuggestions={this.getSectionSuggestions}
        />
      )}
    </Hits>
    <Facets>
      {({ facets, updateFacet }) =>
        facets.map(facet => (
          <button onClick={() => updateFacet(facet.name)}>{facet.name}</button>
        ))
      }
    </Facets>
  </InstantSearch>
);
```

Users would be able to place as many of the same element as they want and the values / callbacks for each will simply be passed in to the render function to be rendered as desired.

**Comment by Haroenv** [comment] 2018-07-13 15:12
duplicate of https://github.com/algolia/react-instantsearch/issues/667

We haven't yet made a change like this, because it's quite complex to make an architecture that works with both the HoCs we have already (connectors) and exporting the render props. 

I'll close this issue, but thanks for your input here!

**Comment by Haroenv** [comment] 2018-07-13 15:13
Note that you should already be able to wrap the HoCs we provide in render props on your own

**Closed by Haroenv** 2018-07-13 15:12 UTC
Labels: Feedback

**Comment by clayne11** [comment] 2018-07-13 15:58
@Haroenv I just discovered the connect components, thanks!
