### ISSUE TITLE
Algolia's Nextjs example isn't working because of hydrateMetadata

### ISSUE THREAD

**Issue by Kerim-Willem** [algolia/react-instantsearch#2986] opened 2020-11-05 10:01 UTC
Hi there,

I want to use Algolia's example of react-instantsearch with Nextjs. However, the code is breaking. I tried to downgrade the version to at least version 6.6 but it's not working. 

I'm getting the error: 

`Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at hydrateMetadata (/Desktop/algolia-next/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:558:32)
    at createInstantSearchManager (/Desktop/algolia-next/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:126:15)
    at new InstantSearch (/Desktop/algolia-next/node_modules/react-instantsearch-core/dist/cjs/widgets/InstantSearch.js:111:72)
    at processChild (/Desktop/algolia-next/node_modules/react-dom/cjs/react-dom-server.node.development.js:2846:14)
    at resolve (/Desktop/algolia-next/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Desktop/algolia-next/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Desktop/algolia-next/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Desktop/algolia-next/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/Desktop/algolia-next/node_modules/next/dist/next-server/server/render.js:81:16)
    at renderPage (/Desktop/algolia-next/node_modules/next/dist/next-server/server/render.js:283:20)
    at /Desktop/algolia-next/.next/server/static/development/pages/_document.js:651:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Desktop/algolia-next/.next/server/static/development/pages/_document.js:206:24)
    at _next (/Desktop/algolia-next/.next/server/static/development/pages/_document.js:228:9)
    at /Desktop/algolia-next/.next/server/static/development/pages/_document.js:235:7
    at new Promise (<anonymous>)`

**Comment by Haroenv** [comment] 2020-11-05 10:24
ah, this seems to be because it took 6.7.0 for dom, but 6.8.2 for core, which indeed aren't compatible, but I don't see how to fix that directly. I've fixed the example for now by updating to 6.8.2 and it works

**Comment by Haroenv** [comment] 2020-11-05 10:24
this however is a duplicate of #2978 I think, so I'll close it here

**Closed by Haroenv** 2020-11-05 10:24 UTC

**Comment by Kerim-Willem** [comment] 2020-11-05 10:30
Thank you!
