### ISSUE TITLE
connectInfiniteHits bug

### ISSUE THREAD

**Issue by sptaszek92** [algolia/react-instantsearch#2464] opened 2019-05-17 09:03 UTC
**Describe the bug 🐛**

I'm having an issue with `connectInfiniteHits` connector.
I've implemented it some time ago and everything worked perfectly. Last days I've noticed that I'm not getting the full response from the connector.  And more specifically - the prop 'hasMore' is returning 'false' when it shouldn't.

**To Reproduce 🔍**

For example:
I have 18 hits. I'm using infinite scroll, 5 items per page. The connector gives me a prop 'hasMore' which says if I should continue refining or stop. After each refresh of the app the prop 'hasMore' returns 'false' on different hits amount. Sometimes it stops on 5 hits, 13 hits and sometimes it gives me the full response with 18hits. It happens randomly. I've checked all my code, nothings changed since it was working fine.

To simplify things, and for debugging I'm just doing:
```js
import React, { Component } from 'react'
import { connectInfiniteHits } from 'react-instantsearch/connectors'

class InfiniteHits extends Component {
  componentDidUpdate () {
    console.warn(this.props.hits.length, this.props.hasMore)
    if (this.props.hasMore) {
      this.props.refine()
    }
  }

  render () {
    return <div>test</div>
  }
}


export default connectInfiniteHits(InfiniteHits)
```

 and after each refresh of the page the final log shows me different response.

I also logged the `page` inside the `onSearchStateChange` function of the `InstantSearch` component and it seems to jump sometimes into high values. 

Does someone have similar problem? Is there a bug with the `page` prop?

**Comment by eunjae-lee** [comment] 2019-05-17 11:19
Hello, thanks for reaching us.
Could you share with us a reproducible example?
It will help us find the problem.
You can use [this template](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/React+InstantSearch/infinite-scroll) to skip the boilerplate part.
And please tell me which version of react-instantsearch you're using.

**Comment by sptaszek92** [comment] 2019-05-17 12:53
Hi, I'm using react-instantsearch version 4.5.1.

My infinite scroll component looks like this:
```
import React, { Component } from 'react'
import InfiniteScroll from 'react-infinite-scroller'
import { connectInfiniteHits } from 'react-instantsearch/connectors'
import PropTypes from 'prop-types'

class InfiniteHits extends Component {
  get hits () {
    const { hitComponent, hits, viewedFilterValue } = this.props
    const HitComponent = hitComponent

    return hits
      .map((hit, index) => <HitComponent
        key={hit.objectID}
        hit={hit}
        hitNumber={index}
        viewedFilterValue={viewedFilterValue}
      />)
  }

  render () {
    return <InfiniteScroll
      pageStart={0}
      loadMore={this.props.refine}
      hasMore={this.props.hasMore}
      className={this.props.infiniteScrollClass}
    >
      {this.hits}
    </InfiniteScroll>
  }
}

InfiniteHits.defaultProps = {
  forceRefreshAlgolia: () => {},
  hits: []
}

InfiniteHits.propTypes = {
  hits: PropTypes.array.isRequired
}

export default connectInfiniteHits(InfiniteHits)
```

My InstantSearch component is quite complex:

```
<InstantSearch
        appId={process.env.REACT_APP_ALGOLIA_APP_ID}
        apiKey={process.env.REACT_APP_ALGOLIA_API_KEY}
        indexName={`${process.env.REACT_APP_ALGOLIA_PREFIX}_${this.state.indexName}`}
        onSearchStateChange={this.onChangeSearchState}
        searchState={this.props.searchState}
        refresh={this.state.refresh}
      >
        <Configure {...configureProps} filters={this.parseFiltersToQuery() + this.state.objectIdFilters} />
        <ComposedComponent
          addFilter={this.addFilter}
          removeFilter={this.removeFilter}
          updateFilter={this.updateFilter}
          changeIndex={this.changeIndex}
          forceRefresh={this.forceRefresh}
          addObjectIdFilters={this.addObjectIdFilters}
          {...this.props}
        />
      </InstantSearch>
```

where:
```
onChangeSearchState = (searchState) => {
    const pureFilters = pipe(
      pathOr('', ['configure', 'filters']),
      split(/AND objectID:/),
      head
    )(searchState)
    const lensConfigureFilters = lensPath(['configure', 'filters'])
    const removeObjectIdFilters = set(lensConfigureFilters, pureFilters)
    const searchStateUrl = pipe(
      removeObjectIdFilters
    )(searchState)

    const updateUrlWithSearchState = () => {
      return this.setState({ refresh: false }, () =>
        this.props.history.push(`${this.props.location.pathname}?${searchStateToUrl(searchStateUrl)}`))
    }

    this.props.onChangeSearchState({ ...searchState, ...this.state.filters, ...this.state.optionalFilters })

    return when(
      equals(true),
      updateUrlWithSearchState
    )(this.props.shouldUpdateUrl)
  }
```

The application is quite complex to share all of the code.

What I noticed that after calling `this.props.refine()` the page number is increased but the new hits are not returned inside the `connectInfiniteHits` connector...

**Comment by eunjae-lee** [comment] 2019-05-17 14:11
Hello, thanks for the code.

However it's hard for us to find out the problem.
As you said the application is complex, could you isolate the related part into a reproducible example?
The link is here: https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/07dc3125f75c68334bc3868faa92ac163ad44030/src/React%20InstantSearch
I notice you are using an old version(`4.5.1`) of React InstanceSearch. We highly recommend you to upgrade to the latest version(`5.6.0`), though.

**Comment by sptaszek92** [comment] 2019-05-21 10:00
I'm sorry, but It's really hard to isolate that part of the application.
I've upgraded to the latest version yesterday and now I'm having a different problem with the infinite scroll itself.
Now the problem is that `refine` doesn't return a promise and I don't know when I'll get my new hits response....
When I attach the `refine` function to a button everything works ok. But when I try to do it with and infinite scroll it falls into a loop, because it doesn't know about the new hits that are coming...

Is there any way to track if there are hits that are about to load?
Why `refine` doesn't return a promise?

**Comment by Haroenv** [comment] 2019-05-21 11:46
It doesn't return a promise, since the function itself will be called again, so there's no need to keep track of internal state regarding refinements within a custom widget

**Comment by frenkelor** [comment] 2019-05-22 10:09
Hi, I'm experiencing the same issue within my react native app
I work on that project and everything went smooth until recently.

I'm going to debug the code right now hop to provide more details.

I don't know if this is helping but we have a similar setup on our web platform and everything it working fine the only difference is we are not using `connectInfiniteHits`  we are using  `connectHits` from 
`import { connectHits } from 'react-instantsearch-dom';`


example 

```
import {
  InstantSearch,
  connectSearchBox,
  connectInfiniteHits,
  Configure,
} from 'react-instantsearch-native';
import algoliasearch from 'algoliasearch';

const SearchBox = compose(
  withTheme,
  connectSearchBox,
)(function SearchInput({
  refine,
  currentRefinement,
  theme,
  onChange,
  isSearchStalled,
}) {
  return (
    <SearchRoot>
      <SearchBoxInput
        tintColor={theme.colors.pinkSwan}
        onChangeText={text => {
          refine(text);
          onChange(text);
        }}
        value={currentRefinement}
        placeholder="Search Something"
        clearButtonMode="always"
        spellCheck={false}
        autoCorrect={false}
        autoCapitalize="none"
        autoFocus
      />
      {isSearchStalled ? <LinearProgress style={{ height: 2 }} /> : null}
    </SearchRoot>
  );
});

const Results = connectInfiniteHits(
  ({ hits, hasMore, refine, onSelectedItem }) => {
    const onEndReached = () => {
      if (hasMore) {
        refine();
      }
    };
    return (
      <FlatList
        data={hits}
        onEndReached={onEndReached}
        keyExtractor={repo => repo.objectID}
        renderItem={({ item }) => (        
            <Text key={item.objectID}>{item.text}</Text>
        )}
      />
    );
  },
);

const searchClient = algoliasearch(
  'latency',
  '6be0576ff61c053d5f9a3225e2a90f76',
);


class SearchComponent extends Component{
render(){
return (
<SearchInstance
                  indexName="instant_search"
                  searchClient={searchClient}
                >                 
                  <SearchBox onChange={this.onChange} />
                  <Results
                    onSelectedItem={this.onSelectedItem(addTaskTextMutation)}
                  />
                </SearchInstance>);
}
}

```

**Comment by frenkelor** [comment] 2019-05-22 11:24
Ok, I dig deeper into this issue i'm getting `CORS not supported` from the server

**Comment by alexpchin** [comment] 2019-05-23 00:23
It seems that the `refresh` attribute of InstantSearch doesn't reload the hits when when using `connectInfiniteHits`. However, it seems to work with `connectHits`. I've tested with `5.4.0` and also with `5.6.0`.

With `connectInfiniteHits`, you need to fully unmount the InstantSearch component in order to refresh the hits.

**Comment by frenkelor** [comment] 2019-05-23 05:39
I found my problem nothing to do with this bug

**Comment by alexpchin** [comment] 2019-05-23 08:16
Hi, I have just tried to switch to importing 'algoliasearch/reactnative` and manually creating the `searchClient` for the `InstantSearch`. However, this does not solve the problem for me.

**Comment by samouss** [comment] 2019-06-13 13:53
@frenkelor Glad to see that you've solved your issue!

@sptaszek92 Did you manage to fix the issue? If not I know that a reproduction might be complicated to build but it's way easier for us to understand the context behind the issue. We provide a template to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). The `InfiniteHits` component you've provided, I didn't manage to make it work. I've updated the [CodeSandbox](https://codesandbox.io/s/react-instantsearch-infinitehits-infinitescroll-00fv8) with a different infinite scroll component. 

@alexpchin The `refresh` prop is not meant to reload the hits. It's purpose is to clear the cache of the provided `searchClient`. The default Algolia client has an in-memory cache to mitigate the number of requests made by InstantSearch. For some cases it might be interesting to clear it (e.g real time indexing application from the browser). The `connectHits` & `connectInfiniteHits` have nothing to do with this. Could you create a new GitHub issue if you have a different problem. Thanks!

**Comment by sptaszek92** [comment] 2019-06-14 11:59
@samouss 
I've upgraded react-instantsearch to latest version and replaced 'react-infinite-scroller' lib with my own infinite scroll logic. 'react-infinite-scroller' lib had problems with the 'refine' function.
It seems to work now

**Comment by samouss** [comment] 2019-06-14 12:03
@sptaszek92 Thanks for the update! I'm closing the issue. Feel free to open a new one if you have any other problem.

**Closed by samouss** 2019-06-14 12:03 UTC

**Comment by alexpchin** [comment] 2019-07-31 08:32
FYI, this was the response I received from the Algolia team: 

Hi,

Thanks for contacting the Algolia team.

The InfiniteHits component has an internal cache to keep previous results as you load more results on the same page. But this cache is not cleared when using the refresh property on the InstantSearch instance.

Sadly there is no way to clear this cache at this moment, so the solution is to force a full re-render of InstantSearch using the key prop. You can read about this pattern here: https://dev.to/ganderzz/react-controlling-rendering-through-keys-274m

Here's an implementation example that re-render InstantSearch when you click on a Clear cache button (in your real application you could for example listen to an event):

```
class ProfilePhotos extends Component {
  state = {
    cacheTimestamp: 0,
  };

  clearCache = () => {
    this.setState({
      cacheTimestamp: Date.now(),
    });
  };

  componentWillUnmount() {
    clearInterval(this.interval);
  }

  render() {
    return (
        <>
            <button onClick={this.clearCache}>Clear cache</button>
            <InstantSearch
                 appId={appId}
                 apiKey={apiKey}
                 indexName={indexName}
                 key={this.state.cacheTimestamp}
            >
                 <InfiniteHits />
            </InstantSearch>
        </>
    );
  }
}
```

**Comment by Ajmal0197** [comment] 2021-12-23 07:16
> import algoliasearch from 'algoliasearch/reactnative';

Hi, I am getting algoliasearch/reactnative not found.

import algoliasearch from 'algoliasearch/reactnative';

**Comment by Haroenv** [comment] 2022-01-03 10:13
since v4 it's just `algoliasearch` or `algoliasearch/lite` @Ajmal0197
