### ISSUE TITLE
Add ability to add a searchbox for a specific field

### ISSUE THREAD

**Issue by brandon-dewitt** [algolia/react-instantsearch#1502] opened 2018-08-13 21:39 UTC
I have an index of movies and want to search those movies where the title contains 'black' or the logline contains 'battleship'.

I think this could be implemented using multiple searchboxes.
```
<InstantSearch indexName='movies'>
  <SearchBox restrictSearchableAttributes={['title']} />
  <SearchBox restrictSearchableAttributes={['logline']} />
</InstantSearch>
```

Is there a better way to build this query?

**Comment by Haroenv** [comment] 2018-08-14 07:35
```jsx
<InstantSearch indexName='movies'>
  <Index indexName="movies">
    <SearchBox />
    <Configure restrictSearchableAttributes={['title']} />
  </Index>
  <Index indexName="movies">
    <SearchBox />
    <Configure restrictSearchableAttributes={['logline']} />
  </Index>
</InstantSearch>
```

This would solve your issue, unfortunately it's not yet possible to create multiple indices with the same indexName. 

The other solution I can think of is to have two `InstantSearch` components on your page, and synchronise the `searchState`. 

@samouss do you have another suggestion, or maybe an idea if we could make the id something else than the index somehow

**Comment by brandon-dewitt** [comment] 2018-08-14 21:05
@Haroenv I don't think this solution allows me to generate multiple queries.  Search state is an object and can only represent one query so the last query wins.  If I search title for 'black', the search state looks like this:

```
{
  indices: {
    movies: {
      configure: { restrictSearchableAttributes: "title" },
      page: 1
    }
  },
  page: 1,
  query: "black"
}
```

If I then search logline for 'battlefield', the search state gets updated to:

```
{
  indices: {
    movies: {
      configure: { restrictSearchableAttributes: "battlefield" },
      page: 1
    }
  },
  page: 1,
  query: "battlefield"
}
```

Here is an example of a multi query I am trying to generate:
```
[{
  indexName: "movies",
  query: "black",
  facetFilters: [["genres:action"]],
  restrictSearchableAttributes: "name"
}, {
  indexName: "movies",
  query: "battleship",
  facetFilters: [["genres:action"]],
  restrictSearchableAttributes: "logline"
}]
```

It would be great to get the results back as single hits collection so I do not have to worry about any overlap between the two hits collections I get back from this query. 

Maybe query can be an array?

```
{
  indexName: "movies",
  query: [{ value: "black", attributes: "title" }, { value: "battleship", attributes: "logline" }],
  facetFilters: [["genres:action"]]
}
```

**Comment by Haroenv** [comment] 2018-08-15 07:10
Query can unfortunately not be an array, a query is unique within a single search. I think there might be some ways around this, but it’ll come down to merging those two hits in a way that’s reasonable to you, or maybe a single search box that has both; but a toggle to trigger the restrictSearchableAttributes. Since you’re on an enterprise plan, feel free to also reach out to your assigned SE, they might have some other ideas I didn’t think of.

**Comment by samouss** [comment] 2018-08-21 07:47
Duplicate of https://github.com/algolia/react-instantsearch/issues/1109

**Closed by samouss** 2018-08-21 07:47 UTC
