### ISSUE TITLE
Ability to make InstantSearch a controlled component and use searchState props without mounting other components

### ISSUE THREAD

**Issue by aaronbushnell** [algolia/react-instantsearch#1291] opened 2018-05-31 20:51 UTC
**Is your feature request related to a problem? Please describe 🙏**
There are times I'd like to make the `<InstantSearch />` component controlled and it reads as if you can do so [based on the Search state guide](https://community.algolia.com/react-instantsearch/guide/Search_state.html).

However, you can't arbitrarily pass state to the `<InstantSearch />` component without also mounting a true (or virtual) widget like `<SearchBox />` or `<RefinementList />` algolia/instantsearch.js#2054

[Example CodeSandbox of this &rarr;](https://codesandbox.io/s/yjwyyjrp49)

**Describe the solution you'd like 🤔**
I'd like to be able to be able to pass state to the `searchState` prop directly without mounting components like `<SearchBox />`

**Describe alternatives you've considered ✨**
If this isn't possible or it's a major lift then I think areas like the [Search state guide](https://community.algolia.com/react-instantsearch/guide/Search_state.html) and [Routing and URLs guide](https://community.algolia.com/react-instantsearch/guide/Routing.html) could do more to clarify this requirement.

**Comment by gdpsysgarage** [comment] 2018-05-31 21:00
It would be great !!

**Comment by MacKentoch** [comment] 2018-06-21 12:04
I really don't understand the current implementation.
This is completely uncommon (*= users will loose time in implementation*) and too rigid.

Why making things so strange / difficult (*widgets in React-Native?*) when you better give us a Context like API or HOCs (*standard and commonly used ways*)?

**Comment by Haroenv** [comment] 2018-06-21 13:10
There are higher order components available to make your own widgets @MacKentoch, see https://community.algolia.com/react-instantsearch/connectors/

**Comment by MacKentoch** [comment] 2018-06-21 13:33
Yes that is a good start. 

Maybe is that just a problem of documentation (*example of documentation issue with Configure widget saying there is no props*):
<img width="880" alt="capture d ecran 2018-06-21 a 15 22 28" src="https://user-images.githubusercontent.com/11223428/41721840-452ed31a-7567-11e8-9d40-afdfb2789e63.png">


But as an example of strange things is: 
- why would I have to use a `Configure` components in `InstantSearch` parent, when I could just put configure value to some InstantSearch props?

NOTES:
- Please understand I'm not bashing (*would be a waste of time, I have better to do and you too*). But for a service that aims to simplify the life I find React-Native implementation (I can't speak for others I did not even try) to overcomplicated.

- Other than that thank you Algolia for offering a search blazing fast experience for our end users.

**Comment by Haroenv** [comment] 2018-06-21 14:41
Hmm, that example of "no props" is definitely a mistake, it should accept all algolia query parameters. 

The reason we chose to have different components is because we wanted the behaviour be component-based. This works for React on web, but also on Native. 

This is because we see React InstantSearch as a UI-driven framework. This makes it declarative, rather than imperative, and is more readable in our experience. 

You can use the connectors in React Native to replicate any of the components we have on web, and use their behaviour. 

I'm not sure if you've seen our example with React Native ([link](https://github.com/algolia/react-instantsearch/tree/master/examples/react-native/src)), but also there we've been able to make the UI component-based. 

Feedback is definitely welcome, and if you'd have a suggestion of what a better API would be, please let us know!

Oh and thanks for that note, I took your first comment in the wrong way 😄

**Comment by JayAndCatchFire** [comment] 2019-05-16 03:11
I ran into this problem.  In my use case, my search box was site-wide, and keeping it inside a `<InstantSearch>` context would be weird since the search results have their own page.  Given that injecting the `searchState` prop turns the InstantSearch component into a controlled component, I was confounded that injecting the search state didn't work properly without a `<SearchBox />` component somewhere inside.

In the end, I worked around it by creating a custom SearchBox that didn't actually render anything.
```javascript
const InvisibleSearchBox = connectSearchBox(() => null);
```
```jsx
<InstantSearch
  apiKey={algoliaApiKey}
  appId={algoliaAppId}
  indexName="RedactedIndexName"
  onSearchStateChange={state => history.push(`/search?${qs.stringify(state)}`)}
  searchState={qs.parse(search.slice(1))}
>
  <InvisibleSearchBox />
  <Hits hitComponent={Hit} />
  <Pagination />
</InstantSearch>
```

It's a dirty hack I wish I didn't have to do, but it did the job.

**Comment by DreamEmulator** [comment] 2020-08-26 19:34
@JayAndCatchFire I'm stuck doing this kind of hacky stuff too. Even though I am passing InstantSearch the searchState it should have from the seperate screen, it just goes and does what it feels like because the refines have been unmounted. I also agree with MacKentoch. Props are props and you shouldn't use components as some kind of pseudo-prop. It undermines the whole mental model of React.

**Comment by francoischalifour** [comment] 2020-08-27 09:34
That's the way to go @JayAndCatchFire. We refer to these components as [virtual widgets](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#virtual-widgets) in the documentation.

**Comment by joshuabaker** [comment] 2022-04-28 12:00
> This is because we see React InstantSearch as a UI-driven framework. This makes it declarative, rather than imperative, and is more readable in our experience.

React itself is a UI-driven framework, but is powered by state.

Using a component-driven approach inhibits accessing or adjusting the internals in any way by design. In some cases, this is also making some features of Algolia impossible to access (#3451, #3448).

I feel quite strongly that the search state context should be available, and widget components and connectors available for composing convenience.

**Comment by FabienMotte** [comment] 2022-12-19 18:00
Hey!

We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it.

We recommend anyone who is currently using React InstantSearch v6 to [migrate to Hooks](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react-hooks/).

Using React InstantSearch Hooks, you can [access the InstantSearch API and interact with its state](https://www.algolia.com/doc/api-reference/widgets/use-instantsearch/react-hooks/), [create custom connectors](https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/react-hooks/) if hooks are not sufficient for what you are trying to do, and [UI components](https://github.com/algolia/react-instantsearch/tree/master/packages/react-instantsearch-hooks-web/src/ui) will soon be exposed.

**Closed by FabienMotte** 2022-12-19 18:00 UTC
Labels: Type: Feature request, Difficulty: ❄️❄️❄️ hard, Feedback
