### ISSUE TITLE
Snippet white space characters

### ISSUE THREAD

**Issue by noclat** [algolia/react-instantsearch#322] opened 2017-09-13 16:27 UTC
On using the `<Snippet>` element, I end up having some leading and/or trailing white spaces. On the screenshot below, the “what” is a bit shifted to the right:

<img width="220" alt="screen shot 2017-09-13 at 18 17 29" src="https://user-images.githubusercontent.com/1834312/30388446-08e7b82a-98b0-11e7-8606-31ae7eaeb87d.png">

In that example, when inspecting the code, I actually have a line break character at the very beginning of the text (this is copy pasted):

```html
<span class="ais-Highlight"><span class="ais-Highlight__nonHighlighted">
What about setting up a call this week to</span></span>
```

Not sure if bug, or feature request, but it would be nice to apply a `trim()` around the value. Having investigated a bit, that solution seems quite touchy because it needs to edit the `Highlither.js` component which is also used by `<Highlight>` widget, that you might not want to get involved. `trim()` also must affect the white spaces between words.

Or maybe this is not related to React-IS and it happens because of my attribute value set up in the Algolia Index? Or due to the “snippet” feature of Algolia?

**Comment by noclat** [comment] 2017-09-13 16:37
The record actually has a white space:

<img width="150" alt="screen shot 2017-09-13 at 18 35 42" src="https://user-images.githubusercontent.com/1834312/30389159-6640beac-98b2-11e7-8117-a555deb1c545.png">

**Comment by Haroenv** [comment] 2017-09-13 18:58
In this case, you’ll be able to use `connectSnippet` and `trim()` the value

**Comment by mthuret** [comment] 2017-09-14 07:53
I'm closing this as it will be on the user side like @Haroenv mention and as we've seen with @noclat 

The connector to use is `connectHighlight` (which is used for both the Highlight and Snippet widgets). See here: https://community.algolia.com/react-instantsearch/connectors/connectHighlight.html

**Closed by mthuret** 2017-09-14 07:53 UTC

**Comment by Gaurav038** [comment] 2022-04-26 05:36
i am also stuck in similar kind of problem, In react instantSearch in filters Configure value having spaces due to which its showing error... what i have to do now

**Comment by Haroenv** [comment] 2022-04-26 07:48
@Gaurav038 can you create a new issue with reproduction? I don't see how this is related to the issue you commented on. Thanks!

**Comment by Gaurav038** [comment] 2022-04-28 04:51
> 

okk thanks i was thinking its similar
