### ISSUE TITLE
react-instantsearch-native 6.10.0 not updating results list 

### ISSUE THREAD

**Issue by pdugan20** [algolia/react-instantsearch#3019] opened 2021-02-28 05:02 UTC
**Describe the bug 🐛**

Upgraded to 6.10.0, and the FlatList that was populating my results was throwing errors with duplicate keys and the results weren't updating.

**To Reproduce 🔍**

Upgrade to version 6.10.0.

**Expected behavior 💭**

I'd expect that when I enter a search query, the results list would update appropriately.

**Environment:**

 - OS: React Native
 - Version 6.10.0

**Additional context**

I downgraded to 6.8.3 and that seemed to work fine, although I'd guess 6.9.0 would also work fine.

**Comment by eunjae-lee** [comment] 2021-03-01 12:46
Hi @pdugan20 
Can you copy&paste the error messages here?

For your information, I just tried it with this example:
https://github.com/algolia/react-instantsearch/tree/master/examples/react-native

and it worked fine with no error. I'd appreciate if you can create a reproducible example.

**Comment by pdugan20** [comment] 2021-03-01 15:39
Sure! The error message reads:
```
Warning: Encountered two children with the same key, `cpO1hTnUv6rvKiv5jh1V`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

Looks like it's being thrown from the following:
```
- node_modules/algoliasearch-helper/src/functions/find.js:13:3 in find
* http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:350740:22 in <unknown>
- node_modules/string_decoder/lib/string_decoder.js:35:6 in <anonymous>
- node_modules/react-instantsearch-core/dist/cjs/index.js:124:11 in get
* [native code]:null in forEach
- node_modules/react-instantsearch-core/dist/cjs/index.js:118:11 in get
* [native code]:null in <unknown>
- node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
- node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
```

The results list also doesn't stay synced with the value entered into the search field:

<img width="339" alt="Screen Shot 2021-03-01 at 7 28 54 AM" src="https://user-images.githubusercontent.com/1837100/109519124-cfb29080-7a5f-11eb-933e-2f5297727568.png">

That same search on 6.8.3 works fine. I'd guess it works fine on 6.9.0 as well although I'm not sure:

<img width="334" alt="Screen Shot 2021-03-01 at 7 37 40 AM" src="https://user-images.githubusercontent.com/1837100/109520453-1b196e80-7a61-11eb-9197-167ec95188b7.png">

**Comment by pdugan20** [comment] 2021-03-01 16:48
Actually looks like this might just be: https://github.com/algolia/react-instantsearch/issues/3018#issuecomment-787768653?

**Comment by Haroenv** [comment] 2021-03-02 09:16
I think the issue is the same, can you confirm by trying 6.9.0 @pdugan20 ?

**Comment by Haroenv** [comment] 2021-03-02 09:16
I see you posted that in the OP. I'll close this issue since there's others open

**Closed by Haroenv** 2021-03-02 09:16 UTC
