### ISSUE TITLE
How do multiple <Configure /> handle merging parameters?

### ISSUE THREAD

**Issue by pheuter** [algolia/react-instantsearch#1490] opened 2018-08-09 20:58 UTC
Under a single `<InstantSearch>` index I am taking advantage of rendering multiple `<Configure />` widgets as part of custom components I created to apply API parameters not available through the default widgets and connectors. For example, here's a component that renders a select dropdown that sets optional filters:

```typescript
class OptionalFilter extends React.Component {
  render() {
    const { attribute, ...restProps } = this.props;

    return (
      <>
        <ReactSelect
          value={this.state.currentValue}
          onChange={(value: any) => this.setState({ currentValue: value })}
        />
        <Configure
          optionalFilters={`${attribute}:${this.state.currentValue &&
            this.state.currentValue.value}`}
        />
      </>
    );
  }
}
```

My question is this: **How does Algolia handle rendering multiple `<Configure />` components?** If the API parameters do not conflict, does it simply merge them together? If they do conflict, like if I rendered multiple `OptionalFilter` components from above, would it simply take a random one?

**Comment by Haroenv** [comment] 2018-08-10 07:33
That's essentially the case, it's safe to have multiple Configure without any conflicts, but if there are multiple with the same key, or if any of the widgets already have this key (like the case with `facetFilters`) then it will be likely overriden by another. I'm not 100% sure which one will be chosen in that case, and it's something that we might change at a later point, but I think the component that gets mounted the latest will be the parameter that gets added to the URL.

You can sidestep this issue by using `createConnector`, but it's definitely less straightforward than the Configure widget. 

In your use case I think you can (in case you have the issue of mounting multiple) look at the code of `RefinementList` and edit it to work for optional filtering; rather than regular filtering. 

If you have more questions I'm happy to investigate proper solutions if you have other problems

**Comment by samouss** [comment] 2018-08-10 08:52
See https://github.com/algolia/react-instantsearch/issues/693 & https://github.com/algolia/react-instantsearch/issues/725

**Comment by pheuter** [comment] 2018-08-10 14:05
Thanks, I’ll take a look at createConnector as a potential alternative.

**Comment by samouss** [comment] 2018-08-21 07:44
Duplicate of https://github.com/algolia/react-instantsearch/issues/725.

**Closed by samouss** 2018-08-21 07:44 UTC
